### ISSUE TITLE
GPL license?

### ISSUE THREAD

**Issue by jacmoe** [wagnrd/SFMLMath#1]
GPL for two hundred and thirteen lines of code in a header, are you serious? :)

**Comment by wagnrd** [comment]
You know what... No I was not, honestly. Heck I'll remove it, you're right. People should do what ever they want with it.

**Comment by wagnrd** [comment]
I changed it to Unlicense, you're welcome.

**Comment by jacmoe** [comment]
Now we're talking!
Thank you for being a good sport about this.
GPL is a good license for entire applications, not for something that is obviously meant to be used by other developers.
Thanks again! 😄
